title: ChengJiaqi's Homepage
page-top-title: ChengJiaqi
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;程嘉祺
copyright-text: '&copy; ChengJiaqi 2023-2025. All Rights Reserved.'
